services:
  - type: web
    name: ai-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: ELEVENLABS_API_KEY
        value: 
      - key: ELEVENLABS_VOICE_ID
        value: 
      - key: TWILIO_ACCOUNT_SID
        value: 
      - key: TWILIO_AUTH_TOKEN
        value: 
      - key: TWILIO_PHONE_NUMBER
        value: 